### ISSUE TITLE
How to run your model ?

### ISSUE THREAD

**Issue by Ahnassef** [frankeng/CarlaSemiTruckTrailer#1]
Hello frankeng, 

I've come across your semitruck model but I can't run it,  What's your Ubuntu, Carla and Unreal Engine version ? 
Also should I build Carla from so that I could run your model ? and should i follow the tutorial with with different 3D model or should I just skip to step 9

I really appreciate the effort you've done creating this and looking forward to your feedback.

**Comment by frankeng** [comment]
I did it on windows unreal 4.26 carla 9.13
You should only put everything in the carla folder ( inclusing folders)
run make launch and add the vehicle as described in step 9.
Run the manual control that I made, I heard from somebody else that the
coupling was not working.

At the moment I do not have time to look at it.





Op di 18 okt. 2022 om 16:37 schreef Ahnassef ***@***.***>:

**Comment by frankeng** [comment]
Hi @Ahnassef 
I update the read.me could you please read it an try it again if you will get it to work now.

**Comment by Ahnassef** [comment]
Thanks frank for your reply, 

I built your version from source and got every step working except running the manual control python script, I got this error:

```
File "manual_controlSemiTrailer.py" line 247 in restart
blueprint = random.choice(get_actor_blueprints(self.world, "DAFxf", self._actor_generation))
File "/usr/lib/python3.8/random.py", line 290, in choice
raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

I think the blueprint isn't registered correctly, Can you provide any feedback on this issue ?

looking forward to your reply.

**Comment by Ahnassef** [comment]
I've solved it and got it working. Thanks again for the blueprints and your effort.

**Comment by frankeng** [comment]
@Ahnassef Good that you solved it, 
could you please also share your solution, in case other people will have the same problem.
Frank

**Comment by EbyGunner** [comment]
When you print all the available blueprints, the blueprint for the vehicle is given as "'vehicle.daf.dafxf'". Just use this to spawn the truck.

I spawned like this:
truck_bp = self.world.get_blueprint_library().find(truck_description)
transform = random.choice(self.spawn_points)
spawn_points = world.get_map().get_spawn_points()
truck = world.spawn_actor(truck_bp, transform)

Just replace the code in the program
