### ISSUE TITLE
How to get SM_sc_<model_of_vehicle>.fbx file for raycast sensors (RADAR, LiDAR, and Semantic LiDAR) ?

### ISSUE THREAD

**Issue by qpc001** [frankeng/CarlaSemiTruckTrailer#7]
I am putting the Semi TruckTrailer to map, but LiDAR sensor can not detect any points of truck or trailer. Here is the document: 
1. https://carla.readthedocs.io/en/latest/tuto_D_generate_colliders/#4-add-the-mesh-as-collider  
2. https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/

**Comment by josyulavt** [comment]
Hi, how did you accomplish this? thanks!
